name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: lsfile
      run: ls
    - name: Grant execute permission for build-publish-airplay-sdk.sh
      run: chmod +x ./platforms/android/aps-sdk/build-publish-airplay-sdk.sh
    - name: Grant execute permission for gradlew
      run: chmod +x ./platforms/android/aps-sdk/gradlew
    - name: sudo ln -fs /bin/bash /bin/sh
      run: sudo ln -fs /bin/bash /bin/sh
    - name: Build
      run: ./platforms/android/aps-sdk/build-publish-airplay-sdk.sh
